# setup.py
#
# Micropolis, Unix Version.  This game was released for the Unix platform
# in or about 1990 and has been modified for inclusion in the One Laptop
# Per Child program.  Copyright (C) 1989 - 2007 Electronic Arts Inc.  If
# you need assistance with this program, you may contact:
#   http://wiki.laptop.org/go/Micropolis  or email  micropolis@laptop.org.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.  You should have received a
# copy of the GNU General Public License along with this program.  If
# not, see <http://www.gnu.org/licenses/>.
#
#             ADDITIONAL TERMS per GNU GPL Section 7
#
# No trademark or publicity rights are granted.  This license does NOT
# give you any right, title or interest in the trademark SimCity or any
# other Electronic Arts trademark.  You may not distribute any
# modification of this program using the trademark SimCity or claim any
# affliation or association with Electronic Arts Inc. or its employees.
#
# Any propagation or conveyance of this program must include this
# copyright notice and these terms.
#
# If you convey this program (or any modifications of it) and assume
# contractual liability for the program to recipients of it, you agree
# to indemnify Electronic Arts for any liability that those contractual
# assumptions impose on Electronic Arts.
#
# You may not misrepresent the origins of this program; modified
# versions of the program must be marked as such and not identified as
# the original program.
#
# This disclaimer supplements the one included in the General Public
# License.  TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, THIS
# PROGRAM IS PROVIDED TO YOU "AS IS," WITH ALL FAULTS, WITHOUT WARRANTY
# OF ANY KIND, AND YOUR USE IS AT YOUR SOLE RISK.  THE ENTIRE RISK OF
# SATISFACTORY QUALITY AND PERFORMANCE RESIDES WITH YOU.  ELECTRONIC ARTS
# DISCLAIMS ANY AND ALL EXPRESS, IMPLIED OR STATUTORY WARRANTIES,
# INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY,
# FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT OF THIRD PARTY
# RIGHTS, AND WARRANTIES (IF ANY) ARISING FROM A COURSE OF DEALING,
# USAGE, OR TRADE PRACTICE.  ELECTRONIC ARTS DOES NOT WARRANT AGAINST
# INTERFERENCE WITH YOUR ENJOYMENT OF THE PROGRAM; THAT THE PROGRAM WILL
# MEET YOUR REQUIREMENTS; THAT OPERATION OF THE PROGRAM WILL BE
# UNINTERRUPTED OR ERROR-FREE, OR THAT THE PROGRAM WILL BE COMPATIBLE
# WITH THIRD PARTY SOFTWARE OR THAT ANY ERRORS IN THE PROGRAM WILL BE
# CORRECTED.  NO ORAL OR WRITTEN ADVICE PROVIDED BY ELECTRONIC ARTS OR
# ANY AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY.  SOME
# JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR LIMITATIONS ON IMPLIED
# WARRANTIES OR THE LIMITATIONS ON THE APPLICABLE STATUTORY RIGHTS OF A
# CONSUMER, SO SOME OR ALL OF THE ABOVE EXCLUSIONS AND LIMITATIONS MAY
# NOT APPLY TO YOU.


########################################################################
# MicropolisEngine setup file.
# Don Hopkins


from distutils.core import *

setup(
    name='OpenTTDInterface',
    version='1.0',
    description='OpenTTD Simulator Engine Interface',
    author='Chris Sawyer',
    author_email='',
    url='',
    ext_modules=[
        Extension('_openttd', [
'src/core/random_func.cpp',
'src/core/alloc_func.cpp',
'src/core/pool_func.cpp',
'src/core/geometry_func.cpp',
'src/core/math_func.cpp',
'src/core/bitmath_func.cpp',
'src/network/core/core.cpp',
'src/network/core/tcp.cpp',
'src/network/core/packet.cpp',
'src/network/core/tcp_admin.cpp',
'src/network/core/tcp_connect.cpp',
'src/network/core/udp.cpp',
'src/network/core/address.cpp',
'src/network/core/host.cpp',
'src/os/unix/unix.cpp',
'src/network/core/tcp_content.cpp',
'src/network/core/tcp_game.cpp',
'src/network/core/tcp_http.cpp',
'src/network/network.cpp',
'src/network/network_gamelist.cpp',
'src/network/network_client.cpp',
'src/network/network_content_gui.cpp',
'src/network/network_gui.cpp',
'src/network/network_admin.cpp',
'src/network/network_chat_gui.cpp',
'src/network/network_content.cpp',
'src/network/network_server.cpp',
'src/network/network_command.cpp',
'src/network/network_udp.cpp',
'src/crashlog.cpp',
#'src/thread/thread_win32.cpp',
#'src/thread/thread_os2.cpp',
#'src/thread/thread_morphos.cpp',
#'src/thread/thread_none.cpp',
'src/thread/thread_pthread.cpp',
'src/sound/xaudio2_s.cpp',
'src/sound/cocoa_s.cpp',
'src/sound/allegro_s.cpp',
#'src/sound/win32_s.cpp',
'src/sound/sdl_s.cpp',
'src/sound/null_s.cpp',
'src/script/squirrel.cpp',
'src/aircraft_cmd.cpp',
'src/aircraft_gui.cpp',
'src/airport.cpp',
'src/airport_gui.cpp',
'src/animated_tile.cpp',
'src/articulated_vehicles.cpp',
'src/autoreplace_cmd.cpp',
'src/autoreplace.cpp',
'src/autoreplace_gui.cpp',
'src/base_consist.cpp',
'src/bmp.cpp',
'src/bootstrap_gui.cpp',
'src/bridge_gui.cpp',
'src/bridge_map.cpp',
'src/build_vehicle_gui.cpp',
'src/cargoaction.cpp',
'src/cargomonitor.cpp',
'src/cargopacket.cpp',
'src/cargotype.cpp',
'src/cheat.cpp',
'src/cheat_gui.cpp',
'src/clear_cmd.cpp',
'src/command.cpp',
'src/company_cmd.cpp',
'src/company_gui.cpp',
'src/console_cmds.cpp',
'src/console.cpp',
'src/console_gui.cpp',
'src/cpu.cpp',
'src/currency.cpp',
'src/os/unix/crashlog_unix.cpp',
'src/date.cpp',
'src/date_gui.cpp',
'src/debug.cpp',
'src/dedicated.cpp',
'src/depot_cmd.cpp',
'src/depot.cpp',
'src/depot_gui.cpp',
'src/disaster_vehicle.cpp',
'src/dock_gui.cpp',
'src/driver.cpp',
'src/economy.cpp',
'src/effectvehicle.cpp',
'src/elrail.cpp',
'src/engine.cpp',
'src/engine_gui.cpp',
'src/error_gui.cpp',
'src/fileio.cpp',
'src/fios.cpp',
'src/fios_gui.cpp',
'src/fontcache.cpp',
'src/fontdetection.cpp',
'src/framerate_gui.cpp',
'src/gamelog.cpp',
'src/genworld.cpp',
'src/genworld_gui.cpp',
'src/gfx.cpp',
'src/gfxinit.cpp',
'src/gfx_layout.cpp',
'src/goal.cpp',
'src/goal_gui.cpp',
'src/graph_gui.cpp',
'src/ground_vehicle.cpp',
'src/group_cmd.cpp',
'src/group_gui.cpp',
'src/heightmap.cpp',
'src/highscore.cpp',
'src/highscore_gui.cpp',
'src/hotkeys.cpp',
'src/industry_cmd.cpp',
'src/industry_gui.cpp',
'src/ini.cpp',
'src/ini_load.cpp',
'src/intro_gui.cpp',
'src/landscape.cpp',
'src/main_gui.cpp',
'src/map.cpp',
'src/misc_cmd.cpp',
'src/misc.cpp',
'src/misc_gui.cpp',
'src/mixer.cpp',
'src/music.cpp',
'src/music_gui.cpp',
'src/newgrf_airport.cpp',
'src/newgrf_airporttiles.cpp',
'src/newgrf_canal.cpp',
'src/newgrf_cargo.cpp',
'src/newgrf_commons.cpp',
'src/newgrf_config.cpp',
'src/newgrf.cpp',
'src/newgrf_debug_gui.cpp',
'src/newgrf_engine.cpp',
'src/newgrf_generic.cpp',
'src/newgrf_gui.cpp',
'src/newgrf_house.cpp',
'src/newgrf_industries.cpp',
'src/newgrf_industrytiles.cpp',
'src/newgrf_object.cpp',
'src/newgrf_railtype.cpp',
'src/newgrf_sound.cpp',
'src/newgrf_spritegroup.cpp',
'src/newgrf_station.cpp',
'src/newgrf_storage.cpp',
'src/newgrf_text.cpp',
'src/newgrf_town.cpp',
'src/newgrf_townname.cpp',
'src/news_gui.cpp',
'src/object_cmd.cpp',
'src/object_gui.cpp',
'src/openttd.cpp',
'src/order_backup.cpp',
'src/order_cmd.cpp',
'src/order_gui.cpp',
'src/osk_gui.cpp',
'src/pbs.cpp',
'src/progress.cpp',
'src/rail_cmd.cpp',
'src/rail.cpp',
'src/rail_gui.cpp',
'src/rev.cpp',
'src/road_cmd.cpp',
'src/road.cpp',
'src/road_gui.cpp',
'src/road_map.cpp',
'src/roadstop.cpp',
'src/roadveh_cmd.cpp',
'src/roadveh_gui.cpp',
'src/screenshot.cpp',
'src/sdl.cpp',
'src/settings.cpp',
'src/settings_gui.cpp',
'src/ship_cmd.cpp',
'src/ship_gui.cpp',
'src/signal.cpp',
'src/signs_cmd.cpp',
'src/signs.cpp',
'src/signs_gui.cpp',
'src/smallmap_gui.cpp',
'src/sound.cpp',
'src/spritecache.cpp',
'src/spriteloader/grf.cpp',
'src/sprite.cpp',
'src/station_cmd.cpp',
'src/station.cpp',
'src/station_gui.cpp',
'src/statusbar_gui.cpp',
'src/story.cpp',
'src/story_gui.cpp',
'src/string.cpp',
'src/stringfilter.cpp',
'src/strings.cpp',
'src/subsidy.cpp',
'src/subsidy_gui.cpp',
'src/terraform_cmd.cpp',
'src/terraform_gui.cpp',
'src/textbuf.cpp',
'src/texteff.cpp',
'src/textfile_gui.cpp',
'src/tgp.cpp',
'src/tilearea.cpp',
'src/tile_map.cpp',
'src/timetable_cmd.cpp',
'src/timetable_gui.cpp',
'src/toolbar_gui.cpp',
'src/town_cmd.cpp',
'src/town_gui.cpp',
'src/townname.cpp',
'src/train_cmd.cpp',
'src/train_gui.cpp',
'src/transparency_gui.cpp',
'src/tree_cmd.cpp',
'src/tree_gui.cpp',
'src/tunnelbridge_cmd.cpp',
'src/tunnel_map.cpp',
'src/vehicle_cmd.cpp',
'src/vehicle.cpp',
'src/vehicle_gui.cpp',
'src/vehiclelist.cpp',
'src/viewport.cpp',
'src/viewport_gui.cpp',
'src/viewport_sprite_sorter_sse4.cpp',
'src/void_cmd.cpp',
'src/water_cmd.cpp',
'src/waypoint_cmd.cpp',
'src/waypoint.cpp',
'src/waypoint_gui.cpp',
'src/widget.cpp',
'src/window.cpp',
'src/saveload/industry_sl.cpp',
'src/saveload/airport_sl.cpp',
'src/saveload/cheat_sl.cpp',
'src/saveload/vehicle_sl.cpp',
'src/saveload/depot_sl.cpp',
'src/saveload/oldloader.cpp',
'src/saveload/cargopacket_sl.cpp',
'src/saveload/strings_sl.cpp',
'src/saveload/company_sl.cpp',
'src/saveload/order_sl.cpp',
'src/saveload/game_sl.cpp',
'src/saveload/oldloader_sl.cpp',
'src/saveload/saveload.cpp',
'src/saveload/station_sl.cpp',
'src/saveload/engine_sl.cpp',
'src/saveload/subsidy_sl.cpp',
'src/saveload/newgrf_sl.cpp',
'src/saveload/map_sl.cpp',
'src/saveload/gamelog_sl.cpp',
'src/saveload/story_sl.cpp',
'src/saveload/linkgraph_sl.cpp',
'src/saveload/misc_sl.cpp',
'src/saveload/afterload.cpp',
'src/saveload/group_sl.cpp',
'src/saveload/town_sl.cpp',
'src/saveload/ai_sl.cpp',
'src/saveload/storage_sl.cpp',
'src/saveload/cargomonitor_sl.cpp',
'src/saveload/animated_tile_sl.cpp',
'src/saveload/economy_sl.cpp',
'src/saveload/autoreplace_sl.cpp',
'src/saveload/labelmaps_sl.cpp',
'src/saveload/waypoint_sl.cpp',
'src/saveload/object_sl.cpp',
'src/saveload/goal_sl.cpp',
'src/saveload/signs_sl.cpp',
'src/3rdparty/md5/md5.cpp',
'src/misc/countedobj.cpp',
'src/misc/getoptdata.cpp',
'src/misc/dbg_helpers.cpp',
'src/game/game_text.cpp',
'src/script/api/script_town.cpp',
'src/script/api/script_order.cpp',
'src/script/api/script_admin.cpp',
'src/script/api/script_news.cpp',
'src/script/api/script_tilelist.cpp',
'src/script/api/script_gamesettings.cpp',
'src/script/api/script_townlist.cpp',
'src/script/api/script_enginelist.cpp',
'src/script/api/script_industrytype.cpp',
'src/script/api/script_subsidylist.cpp',
'src/script/api/script_bridgelist.cpp',
'src/script/api/script_client.cpp',
'src/script/api/script_storypagelist.cpp',
'src/script/api/script_station.cpp',
'src/script/api/script_game.cpp',
'src/script/api/script_map.cpp',
'src/script/api/script_window.cpp',
'src/script/api/script_testmode.cpp',
'src/script/api/script_controller.cpp',
'src/script/api/script_execmode.cpp',
'src/script/api/script_rail.cpp',
'src/script/api/script_signlist.cpp',
'src/script/api/script_depotlist.cpp',
'src/script/api/script_railtypelist.cpp',
'src/script/api/script_industrytypelist.cpp',
'src/script/api/script_event_types.cpp',
'src/script/api/script_engine.cpp',
'src/script/api/script_cargomonitor.cpp',
'src/script/api/script_date.cpp',
'src/script/api/script_tunnel.cpp',
'src/script/api/script_group.cpp',
'src/script/api/script_goal.cpp',
'src/script/api/script_infrastructure.cpp',
'src/script/api/script_log.cpp',
'src/script/api/script_vehiclelist.cpp',
'src/script/api/script_grouplist.cpp',
'src/script/api/script_industrylist.cpp',
'src/script/api/script_list.cpp',
'src/script/api/script_marine.cpp',
'src/script/api/script_vehicle.cpp',
'src/script/api/script_viewport.cpp',
'src/script/api/script_cargolist.cpp',
'src/script/api/script_sign.cpp',
'src/script/api/script_object.cpp',
'src/script/api/script_cargo.cpp',
'src/script/api/script_airport.cpp',
'src/script/api/script_event.cpp',
'src/script/api/script_tile.cpp',
'src/script/api/script_base.cpp',
'src/script/api/script_subsidy.cpp',
'src/script/api/script_industry.cpp',
'src/script/api/script_text.cpp',
'src/script/api/script_accounting.cpp',
'src/script/api/script_bridge.cpp',
'src/script/api/script_story_page.cpp',
'src/script/api/script_company.cpp',
'src/script/api/script_storypageelementlist.cpp',
'src/script/api/script_clientlist.cpp',
'src/script/api/script_error.cpp',
'src/script/api/script_companymode.cpp',
'src/script/api/script_waypointlist.cpp',
'src/script/api/script_waypoint.cpp',
'src/script/api/script_stationlist.cpp',
'src/script/api/script_road.cpp',
'src/script/api/script_basestation.cpp',
'src/script/script_info_dummy.cpp',
'src/script/script_instance.cpp',
'src/script/script_scanner.cpp',
'src/script/squirrel_std.cpp',
'src/script/script_info.cpp',
'src/script/script_config.cpp',
'src/blitter/32bpp_anim_sse4.cpp',
'src/blitter/32bpp_optimized.cpp',
'src/blitter/32bpp_sse2.cpp',
'src/blitter/8bpp_base.cpp',
'src/blitter/8bpp_optimized.cpp',
'src/blitter/8bpp_simple.cpp',
'src/blitter/32bpp_ssse3.cpp',
'src/blitter/null.cpp',
'src/blitter/32bpp_anim.cpp',
'src/blitter/32bpp_simple.cpp',
'src/blitter/32bpp_sse4.cpp',
'src/blitter/32bpp_base.cpp',
'src/blitter/32bpp_anim_sse2.cpp',
'src/blitter/base.cpp',
'src/game/game_info.cpp',
'src/game/game_config.cpp',
#'src/game/game_text.cpp',
'src/game/game_core.cpp',
'src/game/game_instance.cpp',
'src/game/game_scanner.cpp',
'src/pathfinder/yapf/yapf_road.cpp',
'src/pathfinder/yapf/yapf_ship.cpp',
'src/pathfinder/yapf/yapf_rail.cpp',
'src/pathfinder/npf/queue.cpp',
'src/pathfinder/npf/npf.cpp',
'src/pathfinder/npf/aystar.cpp',
'src/pathfinder/opf/opf_ship.cpp',
'src/linkgraph/linkgraph_gui.cpp',
'src/linkgraph/mcf.cpp',
'src/linkgraph/linkgraphschedule.cpp',
'src/linkgraph/linkgraph.cpp',
'src/linkgraph/flowmapper.cpp',
'src/linkgraph/linkgraphjob.cpp',
'src/linkgraph/refresh.cpp',
'src/linkgraph/demands.cpp',
#'src/music/libtimidity.cpp',
#'src/music/bemidi.cpp',
#'src/music/os2_m.cpp',
'src/music/extmidi.cpp',
'src/music/cocoa_m.cpp',
'src/music/allegro_m.cpp',
#'src/music/fluidsynth.cpp',
'src/music/null_m.cpp',
#'src/music/qtmidi.cpp',
'src/music/dmusic.cpp',
#'src/music/win32_m.cpp',
'src/music/midifile.cpp',
'src/3rdparty/squirrel/sqstdlib/sqstdaux.cpp',
'src/3rdparty/squirrel/sqstdlib/sqstdmath.cpp',
#'src/3rdparty/squirrel/sqstdlib/sqstdstring.cpp',
#'src/3rdparty/squirrel/sqstdlib/sqstdrex.cpp',
'src/3rdparty/squirrel/squirrel/sqmem.cpp',
'src/3rdparty/squirrel/squirrel/sqfuncstate.cpp',
'src/3rdparty/squirrel/squirrel/sqbaselib.cpp',
'src/3rdparty/squirrel/squirrel/sqtable.cpp',
'src/3rdparty/squirrel/squirrel/sqvm.cpp',
'src/3rdparty/squirrel/squirrel/sqobject.cpp',
'src/3rdparty/squirrel/squirrel/sqclass.cpp',
'src/3rdparty/squirrel/squirrel/sqstate.cpp',
'src/3rdparty/squirrel/squirrel/sqapi.cpp',
'src/3rdparty/squirrel/squirrel/sqdebug.cpp',
'src/3rdparty/squirrel/squirrel/sqlexer.cpp',
'src/3rdparty/squirrel/squirrel/sqcompiler.cpp',
'objs/openttd_wrap.cpp',
'src/widgets/dropdown.cpp',
#'src/strgen/strgen.cpp',
'src/strgen/strgen_base.cpp',
'src/ai/ai_config.cpp',
'src/ai/ai_core.cpp',
'src/ai/ai_gui.cpp',
'src/ai/ai_info.cpp',
'src/ai/ai_instance.cpp',
'src/ai/ai_scanner.cpp',
],
        include_dirs=[
            'src/widgets',
            '/usr/local/include',
            'src/misc',
            'src',
            'src/music',
            'src/core',
            'src/ai',
            'src/blitter',
            'src/depend',
            'src/linkgraph',
            'src/network',
            'src/os',
            'src/saveload',
            'src/game',
            'src/pathfinder',
           #'src/strgen',
            'src/script',
            'src/3rdparty',
            'src/spriteloader',
            'src/3rdparty/squirrel/include',
        ]),
    ]
)


########################################################################
